-- DDL for data mart layer

create or replace TABLE TASK_8_DWH.DATAMART.AIRPORTS_IN_CONTINENTS_COUNTS (
	CONTINENT_NAME VARCHAR(16777216),
	AIRFPORT_COUNT NUMBER(38,0)
);

create or replace TABLE TASK_8_DWH.DATAMART.GENDER_PASSENGER_COUNTS (
	CONTINENT_NAME VARCHAR(16777216),
	COUNTRY_NAME VARCHAR(16777216),
	FLIGHTS_COUNT NUMBER(38,0),
	MALE_COUNT NUMBER(38,0),
	FEMALE_COUNT NUMBER(38,0),
	MALE_PERCENT FLOAT,
	FEMALE_PERCENT FLOAT
);

create or replace TABLE TASK_8_DWH.DATAMART.PASSENGERS_AGE_GROUPS_BY_NATIONALITY (
	NATIONALITY VARCHAR(16777216),
	TOTAL_COUNT NUMBER(38,0),
	PCT_OVER_25 FLOAT,
	PCT_OVER_35 FLOAT,
	PCT_OVER_50 FLOAT
);